from datetime import datetime
from pathlib import Path
import tkinter as tk
from tkinter import filedialog

from diffusion_device.keys import metadata

# Running the script will allow you to choose the folder containing the data (and thus out folder generated by the burst search script)

# Add all the right parameters below

def choose_data_folder():
    root = tk.Tk()
    root.withdraw()
    folder = filedialog.askdirectory(title="Select folder containing AllData.txt / Alldata.txt or TIFF data")
    root.update()
    root.destroy()
    return folder


def find_data_file(folder):
    folder = Path(folder)
    search_folders = [folder]
    out_folder = folder / "out"
    if out_folder.is_dir():
        search_folders.append(out_folder)

    preferred_names = [
        "Alldata.txt",
        "AllData.txt",
        "Alldata_ch1.txt",
        "Alldata_ch2.txt",
        "AllData_ch1.txt",
        "AllData_ch2.txt",
    ]

    for search_folder in search_folders:
        for name in preferred_names:
            candidate = search_folder / name
            if candidate.is_file():
                return candidate

    tif_candidates = []
    for search_folder in search_folders:
        tif_candidates.extend(sorted(search_folder.glob("*.tif")))
        tif_candidates.extend(sorted(search_folder.glob("*.tiff")))

    if tif_candidates:
        return tif_candidates[0]

    raise FileNotFoundError(
        f"No Alldata/AllData text file or TIFF file found in: {folder}"
    )


selected_folder = choose_data_folder()
if not selected_folder:
    raise RuntimeError("No folder selected.")

datapath = str(find_data_file(selected_folder))
json_infos = {}

# Data Type
# One of "single_pos_scan", "multi_pos_scan", "single_pos_image",
# "multi_pos_image", "stack_multi_pos_image"
json_infos['Type of data'] = 'multi_pos_scan'

# delimiter is the delimiter to separate values in file (None for space)
# skiprows is the number of rows to skip
# index are the index to select. List of tuple given to slice().
# transpose is only needed for 'single_pos_scan'. Should transpose?
json_infos['Scan file structure'] = {
    'delimiter': ",",
    'skiprows': 0,
    'index': ((0, 200), (1, 2)),
    'transpose': False,
}

# Location of the data file(s).
# If None, will take the last path part of datapath.
json_infos['Image file name'] = None

# Background file, relative to the image file. None means no background
json_infos['Background file name'] = None

# image file to remove the background coming from the optics (Not chip related)
json_infos['Optics background file name'] = None

# Should the optics background be subtracted instead of divided.
json_infos['Subtract optics background'] = False

# Image exposition time [s]
json_infos['Image exposition time [s]'] = 1

# Background image exposition time [s]
json_infos['Background image exposition time [s]'] = 1

# Optics background image exposition time [s]
json_infos['Optics background image exposition time [s]'] = None

# Height of the channel [m]
json_infos['Wz[m]'] = 27e-6

# Width of the channel [m]
json_infos['Wy[m]'] = 225e-6

# Width of the walls [m] (Only for multiple channel in an image)
json_infos['Wall Width [m]'] = 50e-6

# Number of channels in a file
json_infos['Number of channels in a file'] = 4

# Flow [ulph].
json_infos['Q[ulph]'] = 100

# Reading position at the middle of the image [m]
json_infos['Read Positions [m]'] = [
    750e-6,
    16250e-6,
    39750e-6,
    80034e-6,
]

# Pixel Size [m]
json_infos['Pixel Size [m]'] = 6.7e-6

# order of the region of interest [px]
json_infos['Image border[px] (t, d, l, r)'] = [
    None,
    None,
    None,
    None,
]

# Added option for later processing
json_infos['Mirror data'] = True

# Date [YYYYMMDD]
json_infos['Date [YYYYMMDD]'] = datetime.today().strftime('%Y%m%d')

# Analyte informations
json_infos['Analyte informations'] = '1nM Atto488'

# Buffer informations
json_infos['Buffer informations'] = '1xPBS pH7'

# Device informations
json_infos['Device informations'] = 'Kadi100x50 model 1'

# profile position. None means the mean over Z is used.
json_infos['Z position of scans [m]'] = None

# Where is the flow going for each reading position?
# For scans, only use 'u' up or 'd' down
json_infos['Flow direction (u, d, l, r)'] = [
    'd',
    'u',
    'd',
    'u',
]

# Operator
json_infos['Operator'] = 'Raphaël'

# Success [1-3]
json_infos['Success [1-3]'] = 3

# Temperature [K]
json_infos['Temperature [K]'] = 295

# Viscosity [Pa s]
json_infos['Viscosity [Pa s]'] = 1e-3

# Frame rate for movies
json_infos['Frame rate [1/s]'] = None

# For non constant frames rate
json_infos['Frames times [s]'] = None

# Inlet channel location in multiple pos data.
# (top, bottom, left, right)
# For scan, use only left and right.
json_infos['Inlet location'] = None

# For scans: Is the wall brighter than the channel background?
json_infos['Bright wall?'] = False

metadata.generate_json(datapath, json_infos)
print(f"Metadata generated for: {datapath}")
